"""Add financial planning tables

Revision ID: 9e4e9e98963d
Revises: bf768592f9ba
Create Date: 2026-09-07 11:16:35.262837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4e9e98963d'
down_revision = 'bf768592f9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('income_type', sa.String(length=50), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('shares_expenses', sa.Boolean(), nullable=True),
    sa.Column('has_debts', sa.Boolean(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('monthly_debt_payment', sa.Float(), nullable=True),
    sa.Column('urgent_debt', sa.Boolean(), nullable=True),
    sa.Column('emergency_fund_status', sa.String(length=50), nullable=True),
    sa.Column('emergency_fund_amount', sa.Float(), nullable=True),
    sa.Column('emergency_fund_goal', sa.Float(), nullable=True),
    sa.Column('has_investments', sa.Boolean(), nullable=True),
    sa.Column('investment_amount', sa.Float(), nullable=True),
    sa.Column('monthly_investment', sa.Float(), nullable=True),
    sa.Column('has_retirement', sa.Boolean(), nullable=True),
    sa.Column('current_age', sa.Integer(), nullable=True),
    sa.Column('retirement_age', sa.Integer(), nullable=True),
    sa.Column('lifestyle_budget', sa.Float(), nullable=True),
    sa.Column('priorities', sa.Text(), nullable=True),
    sa.Column('dreams', sa.Text(), nullable=True),
    sa.Column('security_percentage', sa.Float(), nullable=True),
    sa.Column('fixed_expenses_percentage', sa.Float(), nullable=True),
    sa.Column('personal_investment_percentage', sa.Float(), nullable=True),
    sa.Column('travel_percentage', sa.Float(), nullable=True),
    sa.Column('big_goals_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planning_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('is_essential', sa.Boolean(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('can_reduce', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planning_id'], ['financial_planning.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planning_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('monthly_contribution', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planning_id'], ['financial_planning.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_goal')
    op.drop_table('financial_expense')
    op.drop_table('financial_planning')
    # ### end Alembic commands ###
