"""Add wishlist items table

Revision ID: bf768592f9ba
Revises: 59ad0b2ea235
Create Date: 2026-09-02 10:28:59.017720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf768592f9ba'
down_revision = '59ad0b2ea235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
